// src/vin-web/src/app/inventory/inventory-stats-bar/inventory-stats-bar.component.ts
import { CommonModule } from '@angular/common';
import { Component, signal, type OnInit } from '@angular/core';

import { InventoryService } from '../inventory.service';
import type { InventoryStats, VehicleStatus } from '../inventory.model';

@Component({
  selector: 'app-inventory-stats-bar',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './inventory-stats-bar.component.html',
  styleUrl: './inventory-stats-bar.component.css'
})
export class InventoryStatsBarComponent implements OnInit {
  readonly stats = signal<InventoryStats | null>(null);

  constructor(private readonly inventoryService: InventoryService) {}

  ngOnInit(): void {
    this.inventoryService.getStats().subscribe((stats) => {
      this.stats.set(stats);
    });
  }

  // countsByStatus only contains entries for statuses that actually occur
  // (it's built from a SQL GROUP BY, which never emits empty groups) — a
  // status with zero vehicles right now is simply absent from the array,
  // not present with count 0. This looks it up and defaults to 0 so the
  // template never has to special-case "missing" vs. "zero."
  countFor(status: VehicleStatus): number {
    return this.stats()?.countsByStatus.find((c) => c.status === status)?.count ?? 0;
  }
}

<!-- Guard on stats() being non-null: nothing renders until the one GET
     resolves, matching the table's own "empty until loaded" behavior. -->
<div class="stats-bar" *ngIf="stats() as s">
  <div>
    {{ countFor('OnLot') }} on lot
    &bull;
    {{ countFor('Auctioned') }} auctioned
    &bull;
    {{ countFor('Sold') }} sold
    &bull;
    {{ s.totalCost | currency }} total cost
  </div>
  <div>
    avg cost {{ s.averageCost | currency }}
    &bull;
    avg margin (sold) {{ s.averageProfitMarginForSold != null ? (s.averageProfitMarginForSold | currency) : '—' }}
    &bull;
    avg {{ s.averageDaysOnLotForSold != null ? (s.averageDaysOnLotForSold | number: '1.0-1') : '—' }} days on lot
  </div>
</div>

// src/vin-web-react/src/inventory/InventoryStatsBar.tsx
import './InventoryStatsBar.css';
import { useInventoryStats } from './useInventoryStats';
import type { InventoryStats, VehicleStatus } from './inventory.model';

const currency = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' });
const days = new Intl.NumberFormat('en-US', { maximumFractionDigits: 1 });

// countsByStatus only contains entries for statuses that actually occur
// (built from a SQL GROUP BY, which never emits empty groups) — a status
// with zero vehicles right now is absent from the array, not present with
// count 0. This looks it up and defaults to 0, same helper Angular's
// InventoryStatsBarComponent has as a class method.
function countFor(stats: InventoryStats, status: VehicleStatus): number {
  return stats.countsByStatus.find((c) => c.status === status)?.count ?? 0;
}

export function InventoryStatsBar() {
  const stats = useInventoryStats();

  // Nothing renders until the one GET resolves — same "empty until loaded"
  // behavior as InventoryTable.
  if (stats == null) {
    return null;
  }

  return (
    <div className="stats-bar">
      <div>
        {countFor(stats, 'OnLot')} on lot
        {' • '}
        {countFor(stats, 'Auctioned')} auctioned
        {' • '}
        {countFor(stats, 'Sold')} sold
        {' • '}
        {currency.format(stats.totalCost)} total cost
      </div>
      <div>
        avg cost {currency.format(stats.averageCost)}
        {' • '}
        avg margin (sold) {stats.averageProfitMarginForSold != null ? currency.format(stats.averageProfitMarginForSold) : '—'}
        {' • '}
        avg {stats.averageDaysOnLotForSold != null ? days.format(stats.averageDaysOnLotForSold) : '—'} days on lot
      </div>
    </div>
  );
}
